<a href="https://colab.research.google.com/github/tvial08/collab/blob/main/Tom_Vial_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
import numpy as np # set of tools

In [ ]:
for i in range(100): # this is a for loop and will output a varibale 100 times
   print(i) # this prints out the variable 'i' each time it loops until the max amount for the loop

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [1]:
for i in range(10): # another for loop
  print('667') # this prints out the variable '667'

667
667
667
667
667
667
667
667
667
667


In [ ]:
for i in range(5,8): # this is a for loop with a range between 5 and 8. Therefore it will output 3 numbers
    print(i) # this prints out the variable 'i' each time it loops until the max amount for the loop. The last number in the range is not inclusive

5
6
7


In [ ]:
for i in range(3): # this is a for loop that will output 3 numbers
    print( "Test Number: " , i ) # this prints out the words "Test Number" followed by the variable 'i' which holds the values from 0 to 2 ( which is 3 numbers ) because python starts counting from 0 instead of 1

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x): # This is defining a square function
    return x**2 

In [ ]:
square(5) # square is the word for the squared fuction.

25

In [ ]:
square(square(2)) 

16

In [ ]:
square(square(square(2))) 

256

In [ ]:
square(123456) 

15241383936

In [ ]:
square(square(5)) 

625

In [ ]:
def add_two(x): # This is defining a square function
    return x+2 

In [ ]:
add_two(5) # Adds two

7

In [ ]:
square(add_two(5)) 

49

### Logical Branching

In [ ]:
choice = "apple" # we are storing the word "apple" in the variable 'choice'

In [ ]:
if choice == "apple": 

    print("You choose apples.") # this outputs "You choose apples." if true 

else: # Otherwise
    
    print("You did not choose apples.") # this outputs "You did not choose apples." 

You choose apples.


In [ ]:
choice = "orange" # we are storing the word "orange" in the variable 'choice'

In [ ]:
if choice == "apple":
    print("You choose apples.") # this outputs "You choose apples." if true 

else: # Otherwise
    
    print("You did not choose apples.") # this outputs "You did not choose apples."

You did not choose apples.


In [ ]:
choice = "apple" # we are storing the word "apple" in the variable 'choice'

In [ ]:
if choice == "apple": 

    print("You choose apples.") # this outputs "You choose apples." if its true 
    print("Thank you, shop again!") # this outputs "Thank you, shop again!" if true 
    print(2**123) # this outputs the result of 2^123 if true 

elif choice == "orange":
    print("You choose oranges.") # this outputs "You choose oranges." if true 
    print("Thank you, shop again!") # this outputs "Thank you, shop again!" if true 

else: # Otherwise
    
    print("You did not choose apples or oranges.") # this outputs "You did not choose apples or oranges." 
    print("Thank you, shop again!") # this outputs "Thank you, shop again!"

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") # this prompts the user to enter a choice which in this case they entered bananas

Please enter your choice (i.e. apple): bananas


In [ ]:
choice # this outputs what is being held in the variable 'choice'

'bananas'

In [ ]:
if choice == "apple": # this is a nested if then else statement. Double equal means that it will check if both things on either side are equal and will give me a true

    print("You choose apples.") # this outputs "You choose apples." if true 

elif choice == "oranges": 
    print("You choose oranges.") # this outputs "You choose oranges." if true 

else: # Otherwise
    
    print("You did not choose apples or oranges.") # this outputs "You did not choose apples or oranges." 

You did not choose apples or oranges.


#### Coins

In [ ]:
np.random.random() # generate a random number

0.10557506609254497

In [ ]:
np.random.random() > 0.5 # this is used to tell if the number is greater than 0.5 (True) or less than 0.5 (False)

False

In [ ]:
def flip_coin(): # we have defined the variable flip_coin and have given it some function to carry out
    if np.random.random() > 0.5: 
        print("Heads") # if True, it prints out Heads
    else: # Otherwise
        print("Tails") # if False it prints out Tails

In [ ]:
flip_coin() # executing the function

Heads


### Graphics Output

In [ ]:
from IPython.core.display import display, HTML # tools from a library

In [ ]:
display(HTML('<h1>Hello, world!</h1>')) # displays the text "Hello World!" in a Header Format

In [ ]:
def coin(): # we have defined the variable coin and have given it some function to carry out
  return np.random.randint(2) # this gives us a random integer either 0 or 1

In [ ]:
coin() # executing the function

0

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))
# displaying an image of the Heads side of a coin from the Internet

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [ ]:
def show_img(img): # display an image
  display(HTML('<img src=' + img + '>')) # this outputs the image 

In [ ]:
show_img(heads) # executing the function and displaying the heads outcome

In [ ]:
show_img(tails) # executing the function and displaying the tails outcome

In [ ]:
def flip_coin(): # here we are defining a function that will display an image depending on the outcome of the nested if then else statement

    if coin():
        show_img(heads) # this will show the image for heads if true
    else:
        show_img(tails) # this will show the image for tails if false

In [ ]:
flip_coin() # here we are executing the function 

In [ ]:
for i in range(5): # here we are executing the function in a for loop which will give us 5 outputs 
    flip_coin()

In [ ]:


if coin(): # here we have a function that will display an image depending on the outcome of the nested if then else statement

  show_img(heads) # this will show the image for heads if true

else:

  show_img(tails) # this will show the image for tails if false

### Cards

In [ ]:
def shuffle(x): # we have defined the variable shuffle and have given it some function to carry out
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        print(j,x)
    return x

In [ ]:
a = np.arange(52) # here we have assigned an array with 52 positions/numbers to the variable 'a'

In [ ]:
shuffle(a) #executing the function 

33 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 51 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 33]
23 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 50
 24 25 26 27 28 29 30 31 32 51 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 23 33]
21 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 49 22 50
 24 25 26 27 28 29 30 31 32 51 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 21 23 33]
47 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 49 22 50
 24 25 26 27 28 29 30 31 32 51 34 35 36 37 38 39 40 41 42 43 44 45 46 48
 47 21 23 33]
28 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 49 22 50
 24 25 26 27 48 29 30 31 32 51 34 35 36 37 38 39 40 41 42 43 44 45 46 28
 47 21 23 33]
35 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 49 22 50
 24 25 26 27 48 29 30 31 32 51 34 46 36 37 38 39 40 41 42 43 44 45 35 28
 47 21 23 33]
21 [ 0  1  2  3  4  5 

array([ 0, 38, 26, 22, 51, 25,  6,  3, 11,  1, 46, 32, 30,  7, 19, 42, 14,
       31, 20, 24,  5, 44, 48,  2, 45, 41, 18, 43, 39,  8, 15, 40, 12, 36,
       16,  4, 27, 29, 17, 37, 34,  9, 13, 10, 50, 49, 35, 28, 47, 21, 23,
       33])

In [ ]:
np.random.permutation(52) # This is just a simpler and easier way of executing the function 

array([47, 30, 40, 27, 50, 48, 32, 18, 43, 22, 17, 34, 37, 46, 35, 29, 24,
       13,  9, 16,  1, 45, 10, 14, 33,  5, 23, 42, 12,  7, 31,  3, 20, 25,
       21, 38, 49,  2,  6, 26, 44,  4, 41, 19, 15, 11,  0,  8, 51, 39, 36,
       28])

### Speed Test

In [ ]:
%%timeit
shuffle(a) # this is an easy way of getting the times for the execution of this function

Streaming output truncated to the last 5000 lines.
 34  3  4 28]
4 [20 41 38 25 47 27 46 35 32 23 39 29 15 19 43 24 49  2  1 18  8 12 16 14
 42 13  6 33 44 48 21 31  9 11 37  7 17 51 26 50 45 40 22  5  0 30 36 10
 34  3  4 28]
29 [20 41 38 25 47 27 46 35 32 23 39 29 15 19 43 24 49  2  1 18  8 12 16 14
 42 13  6 33 44 11 21 31  9 48 37  7 17 51 26 50 45 40 22  5  0 30 36 10
 34  3  4 28]
19 [20 41 38 25 47 27 46 35 32 23 39 29 15 19 43 24 49  2  1  9  8 12 16 14
 42 13  6 33 44 11 21 31 18 48 37  7 17 51 26 50 45 40 22  5  0 30 36 10
 34  3  4 28]
1 [20 31 38 25 47 27 46 35 32 23 39 29 15 19 43 24 49  2  1  9  8 12 16 14
 42 13  6 33 44 11 21 41 18 48 37  7 17 51 26 50 45 40 22  5  0 30 36 10
 34  3  4 28]
3 [20 31 38 21 47 27 46 35 32 23 39 29 15 19 43 24 49  2  1  9  8 12 16 14
 42 13  6 33 44 11 25 41 18 48 37  7 17 51 26 50 45 40 22  5  0 30 36 10
 34  3  4 28]
15 [20 31 38 21 47 27 46 35 32 23 39 29 15 19 43 11 49  2  1  9  8 12 16 14
 42 13  6 33 44 24 25 41 18 48 37  7 17 51 26 5

In [ ]:
%%timeit
np.random.permutation(52) # this is an easy way of getting the times for the execution of this function

3.77 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
np.random.permutation(52) # This is just a simpler and easier way of executing the function 

array([47, 34,  6, 37, 44, 11, 17, 10, 31, 22,  9, 27, 51, 39, 50, 23, 33,
        5, 30, 43,  8, 21, 46, 24, 25,  1, 12, 48, 18, 14, 38,  4, 35, 45,
       36, 16, 40, 42, 19, 49, 15,  0, 29, 28, 32,  3,  2, 13, 41, 26,  7,
       20])

In [ ]:
cards = np.random.permutation(52) # here we are assigning the values of the array to the variable 'cards'

In [ ]:
cards # here we are displaying what the variable 'cards' holds

array([45, 27, 43, 11, 12,  6, 41, 23,  3, 13, 44, 18, 36, 14, 10, 47,  2,
       21, 22,  1, 40, 42,  9, 34, 46, 19,  4, 17, 51, 31, 49,  7, 32, 28,
       20, 39,  5, 16, 35,  8, 29,  0, 37, 30, 50, 26, 24, 25, 15, 38, 48,
       33])

In [ ]:
cards[0] # here we are asking for the number in the first position of the array

45

In [ ]:
cards[1] # here we are asking for the number in the second position of the array

27

In [ ]:
cards[2] # here we are asking for the number in the third position of the array

43

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>
    
    # this is an image of a deck of cards from the Internet

In [ ]:
np.arange(52).reshape(4,13) # here we are asking for an array of 52 numbers which will be reshaped into 4 rows and 13 columns 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 # this is another way of achieving the same arrangement of 4 rows and 13 columns but with different numbering this time

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 # this is another way of achieving the same arrangement of 4 rows and 13 columns but with different numbering this time

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] # this is an array of suits of cards
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] # this is an array of different cards in a suit

In [ ]:
def card_name(card_number): # we have defined the variable card_name and have given it some function to carry out
    
    suit = card_number//13 # we have assigned this arrangement to the variable 'suit'
    name = card_number%13 # we have assigned this arrangement to the variable 'name'

    return names[name] + " of " + suits[suit] # here we are formating the output to say "___(card) of ___(suit)"

In [ ]:
card_name(0) # here we are executing the function and diplaying the first position of the array using the formating

'Ace of Clubs'

In [ ]:
card_name(51) # here we are executing the function and diplaying the last position of the array using the formating

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) # here we are assigning the values of the array to the variable 'cards'

In [ ]:
top_of_deck         = card_name(cards[0]) # here we are assigning the first position of the array using the formating to the 'variable top_of_deck'
second_card_in_deck = card_name(cards[1]) # here we are assigning the second position of the array using the formating to the 'second_card_in_deck'
last_card_in_deck   = card_name(cards[-1]) # here we are assigning the last position of the array using the formating to the 'last_card_in_deck'

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck # here we are displaying what each variable holds

('Ace of Diamonds', 'Seven of Diamonds', 'Five of Hearts')

In [ ]:
for i in range(5): # this is called a for loop and this one will output a variable 5 times
    print(card_name(cards[i])) # this will output the first five positions of the array using the formating 

Ace of Diamonds
Seven of Diamonds
Nine of Clubs
Four of Clubs
Four of Spades


In [ ]:
for i in range(15): # this is called a for loop and this one will output a variable 15 times
    print(card_name(cards[i])) # this will output the first fifteen positions of the array using the formating 

Ace of Diamonds
Seven of Diamonds
Nine of Clubs
Four of Clubs
Four of Spades
Jack of Hearts
Two of Spades
Ten of Hearts
Nine of Diamonds
Ten of Spades
Four of Diamonds
Two of Clubs
Queen of Hearts
Ten of Diamonds
Eight of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

    #this is a guide to help with the cards in a deck/pack

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" # here we are displaying an image of the Heads side of a card from the Internet
card_url_tail = ".png" # here we are displaying an image of the Tails side of a card from the Internet

In [ ]:
suit = ['k','p','s','l'] # this is an array of suits of cards by the first letter of their suit
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] # this is an array of different cards in a suit in order

In [ ]:
i = np.random.randint(4) # this gives a random integer between 0 and 3 then stores it in variable 'i' 
j = np.random.randint(13) # this gives a random integer between 0 and 12 then stores it in variable 'j' 

In [ ]:
i,j # here we are displaying the positions in the array stored in the variables 'i' and 'j'

(2, 8)

In [ ]:
suit[i] # here we are displaying the corresponding suit based on the position in the array

's'

In [ ]:
card[j] # here we are displaying the corresponding card based on the position in the array

'9'

In [ ]:
from IPython.core.display import display, HTML # tools from a library

In [ ]:
def show_img(img): # here we are defining a function that will display an image
  display(HTML('<img src=' + img + '>')) # this outputs the image 

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail # here we have assigned the heads image, suit, card and tails image to the variable 'img'

In [ ]:
show_img(img) # here we are executing the function

In [ ]:
def card_image(card_number): # we have defined the variable card_image and have given it some function to carry out
    
    i = card_number//13 # we have assigned this arrangement to the variable 'i'
    j = card_number%13 # we have assigned this arrangement to the variable 'j'

    return suit[i]+card[j] # here we are formating the output to say "___(first letter of suit) ___(card)"

In [ ]:
card_image(3) # here we are executing the function

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail # here we are assigning the head image of the card, the corresponding card and the tails image of the card to the variable 'img'

In [ ]:
show_img(img) # here we are executing the function

In [ ]:
for i in range(52): # this is called a for loop and this one will output the image associated with each position of the array a total of 52 times
    img = card_url_head + card_image(i) + card_url_tail 
    show_img(img)